### ISSUE TITLE
Wrong Postition for Channel Tags

### ISSUE THREAD

**Issue by Mg138** [slowstab/dracula#10]
![image](https://user-images.githubusercontent.com/33348966/131235519-3c71ee32-1047-477f-90a8-e4466f698e20.png)

**Comment by slowstab** [comment]
commit d03a34d343e085254fb40e054f5500e9700ac9b7 already fixes that, try to reload discord

**Comment by Mg138** [comment]
FIxed now, but now a new problem emerges.
![image](https://user-images.githubusercontent.com/33348966/131251302-64cc9f8d-6367-495a-882d-32c14ca1c1aa.png)
The # appears to be in the wrong size

**Comment by slowstab** [comment]
if you mean the size is small, that was intentional
if you are talking about the position it should be fixed now, will look like this:
![scrot](https://user-images.githubusercontent.com/36301891/131255932-f9525dac-d6a9-43a7-b378-de7ffc2cbb23.png)

**Comment by Mg138** [comment]
![image](https://user-images.githubusercontent.com/33348966/131272657-1b2cb927-8852-42d5-afff-489e03765a8f.png)
ehhh... new problem.

**Comment by slowstab** [comment]
lol
fixed
![scrot](https://user-images.githubusercontent.com/36301891/131304798-03ec17ea-9f09-4b19-bd32-17f2d46768b2.png)
