### ISSUE TITLE
 Add a button or option to change the color of the details

### ISSUE THREAD

**Issue by MarkozzDav** [slowstab/dracula#5]
Hello friend, the theme is very good, but it would be incredible that the color of the details could be changed and that it is not just purple, in order to give more variety to the theme such as red, blue, yellow, pink ... etc. Very good topic congratulations!

**Comment by slowstab** [comment]
the theme is made with one accent color in mind and is based on the dracula color palette, i would have to rewrite the entire theme to add more color variables and actually use them. aside from that i dont really want to change anything as i personally like the minimal-ish look.

there are a lot of other great themes that are made with more colors in mind so i encourage you to use them and change the colors to your liking, or if you really want you can fork this repo and expirement.

thanks for the feedback!
