### ISSUE TITLE
Code blocks not using dracula colors

### ISSUE THREAD

**Issue by AdrianHDev** [slowstab/dracula#6]
Code blocks could use Dracula's theme colors but don't.

What code blocks look like:
![image](https://user-images.githubusercontent.com/13549227/120942209-63e26280-c6f5-11eb-8714-1bc9915d2116.png)

What code blocks colors should look like:
![image](https://user-images.githubusercontent.com/13549227/120942226-7d83aa00-c6f5-11eb-8dc6-9120b628669b.png)

**Comment by slowstab** [comment]
i have actually tried to do that before for a separate theme but found out discord's codeblock customization through css is extremely limited. discord only provides a small amount of classes for codeblocks making it impossible to incorporate an entire theme color palette.

if you are using powercord, there is a [plugin](https://github.com/Vap0r1ze/vpc-shiki) that solves that by rendering the codeblocks with shiki and giving you full customizability for codeblocks.

i will try to use the dracula color palette for discord's default codeblocks later, but expect something far from complete and probably ugly.
