### ISSUE TITLE
Theme isnt loading 

### ISSUE THREAD

**Issue by HyacinthX** [slowstab/dracula#8]
I had tried this theme along with many others and for some reason, this theme wouldn't load for me discord just stayed the same and I had also tried redownloading the theme along with reloading discord still to no avail. Don't get me wrong I really like this theme's color palette it's so pretty and I don't mean to come off as mean or anything like that I'm just confused, so it could just be me. 
![Screenshot (234)](https://user-images.githubusercontent.com/89533598/130818343-7cb45f5c-9204-40df-934b-420a9a5414ee.png)

**Comment by slowstab** [comment]
fix is already out but its gonna take some time to work again because dns resolvers are painful
